name: Run-PHPUnit-Tests

on:
  push:
    branches:
      - main  # Change this to your branch name if needed
  pull_request:
    branches:
      - main  # Change this to your branch name if needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Adjust the PHP version as needed

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: phpunit FKRedirectTest.php
